symfony:
  build: .  
  volumes:
    - .:/var/www
  volumes_from: 
    - shared

composer:  
  image: atamos/composer:2
  
nginx:
  image: atamos/nginx:2
  ports:
    - 8080:8080
  links:
    - php 
    - mysql
  volumes_from:
    - symfony

php:
  image: atamos/php-fpm:2
  volumes_from:
    - symfony

mysql:
  image: mysql
  volumes_from:
    - mysqldata
  environment:
    MYSQL_DATABASE: symfony
    MYSQL_USER: symfony
    MYSQL_PASSWORD: symfony
    MYSQL_ALLOW_EMPTY_PASSWORD: yes

shared:
  image: atamos/shared:2 
  volumes: 
    - /var/symfony/cache
    - /var/symfony/logs

mysqldata:
   image: busybox
   volumes:
     - /var/lib/mysql2 
